# Site settings
title: Flama’s Front End Toolkit
email: contas@flama.me
description: Tools and frameworks for developing front end at Flama
baseurl: "/front-end-toolkit"
url: "http://flama.is"
twitter_username: studioflama
github_username:  flama

# Build settings
markdown: kramdown
permalink: /title

sass:
  sass_dir: assets/stylesheets/_sass

collections:
  contents:
    output: true
